## GitLab Continuous Integration YAML file

before_script:

after_script:

.common_variables: &common_variables
  BUILD_HOME: /builds/$CI_PROJECT_NAMESPACE
  XDAQ_OS: linux
  XDAQ_ROOT: /opt/xdaq
  LD_LIBRARY_PATH: /opt/xdaq/lib
  EOS_BASE_WEB_DIR: /eos/project/c/cmsgemdaq/www
  EOS_COMMON_WEB_DIR: cmsgemdaq
  EOS_SITE_WEB_DIR: ${PACKAGE_NAME}
  
.slc6setup: &slc6setup
  image: gitlab-registry.cern.ch/cms-gem-daq-project/gemdaq_ci_worker:slc6
  variables: *common_variables

.cc7setup: &cc7setup
  image: gitlab-registry.cern.ch/cms-gem-daq-project/custom_ci_worker:cc7
  variables: *common_variables

stages:
  - build
  - test
  - deploy
  - cleanup

build:slc6:
  <<: *slc6setup
  only:
    - /^issue-.*$/
    - /^.*.hotfix.*$/
    - /^release.*$/
    - master
    - tags
  tags:
  stage: build
  before_script:
    # - ${BUILD_HOME}/config/build/setupMachine.sh
    # - . /etc/profile/xdaq.sh
    - . ${BUILD_HOME}/cmsgemos/setup/etc/profile.d/gemdaqenv.sh
    - . ${BUILD_HOME}/cmsgemos/setup/paths.sh
  script:
    - make all -j8
    - make rpm -j8
  environment:
  variables:
  cache:
  artifacts:
    paths:
      - gem*/lib/**/*.so
      - gem*/rpm/**/*.rpm
      - gem*/rpm/**/*.tar.gz
      - gem*/rpm/**/*.zip
      - gem*/rpm/**/*.tgz
      - gem*/rpm/**/*.tbz2
  coverage: '/Code coverage: \d+\.\d+/'

# run tests using the binary built before
test:slc6:
  <<: *slc6setup
  stage: test
  dependencies:
    - build:slc6
  script:
    - ${BUILD_HOME}/runmytests.sh
  coverage: '/Testing coverage: \d+\.\d+/'

# generate RPMs
buildrpm:slc6:
  <<: *slc6setup
  stage: deploy
  only:
    - tags
    - triggers
  dependencies:
    - build:slc6
  script:
    - make rpm
    - glob gem*/rpm/**/*.rpm

# package and release RPMs
docs:
  <<: *slc6setup
  stage: deploy
  only:
    - tags
    - triggers
    - master
  dependencies:
  script:
    - doxygen -s ${BUILD_HOME}/doc/cmsgemos.cfg >& /dev/null
  coverage: '/Documentation coverage: \d+\.\d+/'

# deploy:
#   only:
#     - tags
#   dependencies:
#     - buildrpm:slc6
#     - buildrpm:cc7
#     - docs # only build docs once, don't need arch versioned docs...
# script:
#     - push python packages to pypi/conda
#     - push RPMs to packagecloud.io
#     - push RPMs to $EOS_WEB_DIR/release/${shorttag}/${OS_VER}/{base,updates,test,devel}, trigger createrepo --update?
#       - if $EOS_WEB_DIR/release/${shorttag}/${OS_VER}/base doesn't exist, create and run createrepo to generate structure
#       - if tag is x.y.0, push RPMs to $EOS_WEB_DIR/release/${shorttag}/${OS_VER}/base
#       - if tag is x.y.z, z > 0 push RPMs to $EOS_WEB_DIR/release/${shorttag}/${OS_VER}/updates
#       - if tag is x.y.z-anything, push RPMs to $EOS_WEB_DIR/release/${shorttag}/${OS_VER}/{test,devel}
#     - push sphinx/rst/md/rtd docs to readthedocs.io
#     - push sphinx/rst/md/rtd docs to $EOS_WEB_DIR/docs/${fulltag}, update doc main page index
#     - push doxygen to $EOS_WEB_DIR/release/${shorttag}/api/html
